const data = [
  { cap: "53021", comune: "Abbadia San Salvatore", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "51021", comune: "Abetone", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "61041", comune: "Acqualagna", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47892", comune: "Acquaviva", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "51031", comune: "Agliana", provincia: "PT", giorni: ["LUN","GIO","VEN","SAB"] },
  { cap: "60020", comune: "Agugliano", provincia: "AN", giorni: ["MAR","MER","VEN"] },
  { cap: "48011", comune: "Alfonsine", provincia: "RA", giorni: ["MAR","MER","VEN"] },
  { cap: "60121", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60122", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60123", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60124", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60125", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60126", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60127", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60128", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60129", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60130", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60131", comune: "Ancona", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "52031", comune: "Anghiari", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "40011", comune: "Anzola dell'Emilia", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "61042", comune: "Apecchio", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "60011", comune: "Arcevia", provincia: "AN", giorni: ["MAR","GIO","VEN"] },
  { cap: "52100", comune: "Arezzo", provincia: "AR", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40050", comune: "Argelato", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "44011", comune: "Argenta", provincia: "FE", giorni: ["MAR","MER","VEN"] },
  { cap: "53041", comune: "Asciano", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "06081", comune: "Assisi", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "61020", comune: "Auditore", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "52032", comune: "Badia Tedalda", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "48012", comune: "Bagnacavallo", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "48010", comune: "Bagnara di Romagna", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50012", comune: "Bagno a Ripoli", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47021", comune: "Bagno di Romagna", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "60010", comune: "Barbara", provincia: "AN", giorni: ["MAR","GIO","SAB"] },
  { cap: "50031", comune: "Barberino di Mugello", provincia: "FI", giorni: ["LUN","MAR","MER","VEN","SAB"] },
  { cap: "50021", comune: "Barberino Val d'Elsa", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "61040", comune: "Barchi", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40052", comune: "Baricella", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "06083", comune: "Bastia Umbra", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41030", comune: "Bastiglia", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40053", comune: "Bazzano", provincia: "BO", giorni: ["MAR","GIO","VEN"] },
  { cap: "61026", comune: "Belforte all'Isauro", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "47814", comune: "Bellaria-Igea Marina", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60030", comune: "Belvedere Ostrense", provincia: "AN", giorni: ["LUN","MER","GIO","VEN"] },
  { cap: "40010", comune: "Bentivoglio", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44033", comune: "Berra", provincia: "FE", giorni: ["MAR","VEN"] },
  { cap: "47032", comune: "Bertinoro", provincia: "FC", giorni: ["LUN","MAR","GIO","SAB"] },
  { cap: "06084", comune: "Bettona", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06031", comune: "Bevagna", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "52011", comune: "Bibbiena", provincia: "AR", giorni: ["LUN","GIO","SAB"] },
  { cap: "40121", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40122", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40123", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40124", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40125", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40126", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40127", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40128", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40129", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40130", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40131", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40132", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40133", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40134", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40135", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40136", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40137", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40138", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40139", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40140", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40141", comune: "Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41030", comune: "Bomporto", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44012", comune: "Bondeno", provincia: "FE", giorni: ["LUN","MER","VEN"] },
  { cap: "47030", comune: "Borghi", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "47893", comune: "Borgo Maggiore", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "61040", comune: "Borgo Pace", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "50032", comune: "Borgo San Lorenzo", provincia: "FI", giorni: ["LUN","GIO","SAB"] },
  { cap: "40021", comune: "Borgo Tossignano", provincia: "BO", giorni: ["MAR","VEN"] },
  { cap: "48013", comune: "Brisighella", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "52021", comune: "Bucine", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "40054", comune: "Budrio", provincia: "BO", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "51011", comune: "Buggiano", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "53022", comune: "Buonconvento", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "47893", comune: "Ca' Rigo", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "61043", comune: "Cagli", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47893", comune: "Cailungo", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "40012", comune: "Calderara di Reno", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "50041", comune: "Calenzano", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60021", comune: "Camerano", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "60020", comune: "Camerata Picena", provincia: "AN", giorni: ["MER","VEN"] },
  { cap: "06042", comune: "Campello sul Clitunno", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "50013", comune: "Campi Bisenzio", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41011", comune: "Campogalliano", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41031", comune: "Camposanto", provincia: "MO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40032", comune: "Camugnano", provincia: "BO", giorni: ["MAR","GIO","VEN"] },
  { cap: "06033", comune: "Cannara", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "59025", comune: "Cantagallo", provincia: "PO", giorni: ["LUN","MER","GIO","VEN"] },
  { cap: "61044", comune: "Cantiano", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "52010", comune: "Capolona", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "50050", comune: "Capraia e Limite", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "52033", comune: "Caprese Michelangelo", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "59015", comune: "Carmignano", provincia: "PO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61021", comune: "Carpegna", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "41012", comune: "Carpi", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "61030", comune: "Cartoceto", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40033", comune: "Casalecchio di Reno", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40020", comune: "Casalfiumanese", provincia: "BO", giorni: ["MAR","VEN"] },
  { cap: "06043", comune: "Cascia", provincia: "PG", giorni: ["MER","VEN"] },
  { cap: "48010", comune: "Casola Valsenio", provincia: "RA", giorni: ["LUN","MER","VEN"] },
  { cap: "47890", comune: "Casole", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "53031", comune: "Casole d'Elsa", provincia: "SI", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "48014", comune: "Castel Bolognese", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60010", comune: "Castel Colonna", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40034", comune: "Castel d'Aiano", provincia: "BO", giorni: ["MAR","GIO","VEN"] },
  { cap: "40022", comune: "Castel del Rio", provincia: "BO", giorni: ["MAR","VEN"] },
  { cap: "40030", comune: "Castel di Casio", provincia: "BO", giorni: ["MAR","GIO","VEN"] },
  { cap: "52016", comune: "Castel Focognano", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "40023", comune: "Castel Guelfo di Bologna", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40013", comune: "Castel Maggiore", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06044", comune: "Castel Ritaldi", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "52018", comune: "Castel San Niccolò", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "40024", comune: "Castel San Pietro Terme", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60030", comune: "Castelbellino", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "47861", comune: "Casteldelci", provincia: "RN", giorni: ["MAR","GIO","VEN"] },
  { cap: "60022", comune: "Castelfidardo", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50051", comune: "Castelfiorentino", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "52020", comune: "Castelfranco di Sopra", provincia: "AR", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "41013", comune: "Castelfranco Emilia", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "60010", comune: "Castelleone di Suasa", provincia: "AN", giorni: ["MAR","GIO","VEN"] },
  { cap: "53011", comune: "Castellina in Chianti", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "40050", comune: "Castello d'Argile", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "40050", comune: "Castello di Serravalle", provincia: "BO", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "53019", comune: "Castelnuovo Berardenga", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "41051", comune: "Castelnuovo Rangone", provincia: "MO", giorni: ["LUN","MER","VEN"] },
  { cap: "60031", comune: "Castelplanio", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "41014", comune: "Castelvetro di Modena", provincia: "MO", giorni: ["LUN","MER","VEN"] },
  { cap: "40055", comune: "Castenaso", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "52029", comune: "Castiglion Fibocchi", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "52043", comune: "Castiglion Fiorentino", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "40035", comune: "Castiglione dei Pepoli", provincia: "BO", giorni: ["MAR","GIO","VEN"] },
  { cap: "06061", comune: "Castiglione del Lago", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "53023", comune: "Castiglione d'Orcia", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "47011", comune: "Castrocaro Terme e Terra del Sole", provincia: "FC", giorni: ["MAR","GIO","VEN"] },
  { cap: "47841", comune: "Cattolica", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41032", comune: "Cavezzo", provincia: "MO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "52022", comune: "Cavriglia", provincia: "AR", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "44042", comune: "Cento", provincia: "FE", giorni: ["LUN","MER","VEN"] },
  { cap: "47898", comune: "Cerbaiola", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "60043", comune: "Cerreto d'Esi", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06041", comune: "Cerreto di Spoleto", provincia: "PG", giorni: ["MER","VEN"] },
  { cap: "50050", comune: "Cerreto Guidi", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "50052", comune: "Certaldo", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "48015", comune: "Cervia", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47521", comune: "Cesena", provincia: "FC", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47522", comune: "Cesena", provincia: "FC", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47042", comune: "Cesenatico", provincia: "FC", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "53040", comune: "Cetona", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "53042", comune: "Chianciano Terme", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "60033", comune: "Chiaravalle", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47894", comune: "Chiesanuova", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "51013", comune: "Chiesina Uzzanese", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "52010", comune: "Chitignano", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "53012", comune: "Chiusdino", provincia: "SI", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "53043", comune: "Chiusi", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "52010", comune: "Chiusi della Verna", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "06010", comune: "Citerna", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "06062", comune: "Città della Pieve", provincia: "PG", giorni: ["MAR","GIO","VEN","SAB"] },
  { cap: "06012", comune: "Città di Castello", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47012", comune: "Civitella di Romagna", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "52041", comune: "Civitella in Val di Chiana", provincia: "AR", giorni: ["LUN","MER","VEN"] },
  { cap: "44021", comune: "Codigoro", provincia: "FE", giorni: ["MAR","VEN"] },
  { cap: "61022", comune: "Colbordolo", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "06050", comune: "Collazzone", provincia: "PG", giorni: ["LUN","MAR","GIO","VEN"] },
  { cap: "53034", comune: "Colle di Val d'Elsa", provincia: "SI", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "44022", comune: "Comacchio", provincia: "FE", giorni: ["MAR","VEN"] },
  { cap: "41033", comune: "Concordia sulla Secchia", provincia: "MO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "48017", comune: "Conselice", provincia: "RA", giorni: ["MAR","MER","VEN"] },
  { cap: "44034", comune: "Copparo", provincia: "FE", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06073", comune: "Corciano", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47853", comune: "Coriano", provincia: "RN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "60013", comune: "Corinaldo", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "52044", comune: "Cortona", provincia: "AR", giorni: ["LUN","MER","VEN"] },
  { cap: "06021", comune: "Costacciaro", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "48010", comune: "Cotignola", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40056", comune: "Crespellano", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "40014", comune: "Crevalcore", provincia: "BO", giorni: ["LUN","MAR","GIO","VEN"] },
  { cap: "60034", comune: "Cupramontana", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "51024", comune: "Cutigliano", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "06053", comune: "Deruta", provincia: "PG", giorni: ["LUN","MAR","GIO","VEN"] },
  { cap: "50062", comune: "Dicomano", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "47891", comune: "Dogana", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "47895", comune: "Domagnano", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "47013", comune: "Dovadola", provincia: "FC", giorni: ["MAR","GIO","VEN"] },
  { cap: "40060", comune: "Dozza", provincia: "BO", giorni: ["LUN","MAR","GIO","VEN"] },
  { cap: "50053", comune: "Empoli", provincia: "FI", giorni: ["LUN","MER","VEN"] },
  { cap: "60044", comune: "Fabriano", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "48018", comune: "Faenza", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47896", comune: "Faetano", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "47891", comune: "Falciano", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "60015", comune: "Falconara Marittima", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "41021", comune: "Fanano", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "61032", comune: "Fano", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61033", comune: "Fermignano", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "44121", comune: "Ferrara", provincia: "FE", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44122", comune: "Ferrara", provincia: "FE", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44123", comune: "Ferrara", provincia: "FE", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44124", comune: "Ferrara", provincia: "FE", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50014", comune: "Fiesole", provincia: "FI", giorni: ["LUN","MER","VEN"] },
  { cap: "45024", comune: "Fiesso Umbertiano", provincia: "RO", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "50063", comune: "Figline Valdarno", provincia: "FI", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "60024", comune: "Filottrano", provincia: "AN", giorni: ["MER","VEN"] },
  { cap: "41034", comune: "Finale Emilia", provincia: "MO", giorni: ["LUN","MER","VEN"] },
  { cap: "41042", comune: "Fiorano Modenese", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47897", comune: "Fiorentino", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "47899", comune: "Fiorina", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "50121", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50122", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50123", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50124", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50125", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50126", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50127", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50128", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50129", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50130", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50131", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50132", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50133", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50134", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50135", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50136", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50137", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50138", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50139", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50140", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50141", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50142", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50143", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50144", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50145", comune: "Firenze", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41022", comune: "Fiumalbo", provincia: "MO", giorni: ["MAR","VEN"] },
  { cap: "52045", comune: "Foiano della Chiana", provincia: "AR", giorni: ["LUN","MER","VEN"] },
  { cap: "06034", comune: "Foligno", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40025", comune: "Fontanelice", provincia: "BO", giorni: ["MAR","VEN"] },
  { cap: "47121", comune: "Forlì", provincia: "FC", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47122", comune: "Forlì", provincia: "FC", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47034", comune: "Forlimpopoli", provincia: "FC", giorni: ["MAR","GIO","VEN","SAB"] },
  { cap: "41043", comune: "Formigine", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44035", comune: "Formignana", provincia: "FE", giorni: ["MER","VEN"] },
  { cap: "06022", comune: "Fossato di Vico", provincia: "PG", giorni: ["MAR","GIO","VEN","SAB"] },
  { cap: "61034", comune: "Fossombrone", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "41044", comune: "Frassinoro", provincia: "MO", giorni: ["MER","VEN"] },
  { cap: "06054", comune: "Fratta Todina", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "61040", comune: "Fratte Rosa", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61021", comune: "Frontino", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "61040", comune: "Frontone", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "50054", comune: "Fucecchio", provincia: "FI", giorni: ["LUN","MER","VEN"] },
  { cap: "48010", comune: "Fusignano", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "61011", comune: "Gabicce Mare", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40041", comune: "Gaggio Montano", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "53013", comune: "Gaiole in Chianti", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "47891", comune: "Galazzano", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "47010", comune: "Galeata", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "40015", comune: "Galliera", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "50050", comune: "Gambassi Terme", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "47035", comune: "Gambettola", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "47043", comune: "Gatteo", provincia: "FC", giorni: ["MAR","MER","VEN"] },
  { cap: "47855", comune: "Gemmano", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "60040", comune: "Genga", provincia: "AN", giorni: ["MER","VEN"] },
  { cap: "06030", comune: "Giano dell'Umbria", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "44020", comune: "Goro", provincia: "FE", giorni: ["MAR","VEN"] },
  { cap: "61012", comune: "Gradara", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40045", comune: "Granaglione", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "40057", comune: "Granarolo dell'Emilia", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50022", comune: "Greve in Chianti", provincia: "FI", giorni: ["MAR","GIO","SAB"] },
  { cap: "40030", comune: "Grizzana Morandi", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "47892", comune: "Gualdicciolo", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "06035", comune: "Gualdo Cattaneo", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "06023", comune: "Gualdo Tadino", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "06024", comune: "Gubbio", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "41052", comune: "Guiglia", provincia: "MO", giorni: ["MER","VEN"] },
  { cap: "40026", comune: "Imola", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50023", comune: "Impruneta", provincia: "FI", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "50064", comune: "Incisa in Val d'Arno", provincia: "FI", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61030", comune: "Isola del Piano", provincia: "PU", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "60035", comune: "Jesi", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44037", comune: "Jolanda di Savoia", provincia: "FE", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "44023", comune: "Lagosanto", provincia: "FE", giorni: ["MAR","VEN"] },
  { cap: "41023", comune: "Lama Mocogno", provincia: "MO", giorni: ["MAR","VEN"] },
  { cap: "51035", comune: "Lamporecchio", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "51036", comune: "Larciano", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "50055", comune: "Lastra a Signa", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "52020", comune: "Laterina", provincia: "AR", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06060", comune: "Lisciano Niccone", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "40042", comune: "Lizzano in Belvedere", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "40050", comune: "Loiano", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "50060", comune: "Londa", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "47020", comune: "Longiano", provincia: "FC", giorni: ["MAR","MER","VEN"] },
  { cap: "60025", comune: "Loreto", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "52024", comune: "Loro Ciuffenna", provincia: "AR", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "52046", comune: "Lucignano", provincia: "AR", giorni: ["MER","VEN"] },
  { cap: "48022", comune: "Lugo", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "61026", comune: "Lunano", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "61023", comune: "Macerata Feltria", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "06063", comune: "Magione", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "60030", comune: "Maiolati Spontini", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "47862", comune: "Maiolo", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "40051", comune: "Malalbergo", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "41053", comune: "Maranello", provincia: "MO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "41054", comune: "Marano sul Panaro", provincia: "MO", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "52047", comune: "Marciano della Chiana", provincia: "AR", giorni: ["LUN","MER","VEN"] },
  { cap: "51010", comune: "Marliana", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "50034", comune: "Marradi", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "06055", comune: "Marsciano", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "40043", comune: "Marzabotto", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "44020", comune: "Masi Torello", provincia: "FE", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "51010", comune: "Massa e Cozzile", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "44025", comune: "Massa Fiscaglia", provincia: "FE", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "48024", comune: "Massa Lombarda", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06056", comune: "Massa Martana", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "40059", comune: "Medicina", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "41036", comune: "Medolla", provincia: "MO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47014", comune: "Meldola", provincia: "FC", giorni: ["MER","VEN"] },
  { cap: "61040", comune: "Mercatello sul Metauro", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "61013", comune: "Mercatino Conca", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "47025", comune: "Mercato Saraceno", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "60030", comune: "Mergo", provincia: "AN", giorni: ["MER","VEN"] },
  { cap: "44026", comune: "Mesola", provincia: "FE", giorni: ["MAR","VEN"] },
  { cap: "44027", comune: "Migliarino", provincia: "FE", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "44020", comune: "Migliaro", provincia: "FE", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "40061", comune: "Minerbio", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "44043", comune: "Mirabello", provincia: "FE", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "41037", comune: "Mirandola", provincia: "MO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47843", comune: "Misano Adriatico", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41121", comune: "Modena", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41122", comune: "Modena", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41123", comune: "Modena", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41124", comune: "Modena", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41125", comune: "Modena", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41126", comune: "Modena", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47015", comune: "Modigliana", provincia: "FC", giorni: ["MAR","GIO","VEN"] },
  { cap: "40062", comune: "Molinella", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "61024", comune: "Mombaroccio", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "47836", comune: "Mondaino", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "61040", comune: "Mondavio", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61037", comune: "Mondolfo", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40063", comune: "Monghidoro", provincia: "BO", giorni: ["MAR","GIO","VEN"] },
  { cap: "60030", comune: "Monsano", provincia: "AN", giorni: ["MAR","GIO","VEN"] },
  { cap: "51015", comune: "Monsummano Terme", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "50050", comune: "Montaione", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "53024", comune: "Montalcino", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "51037", comune: "Montale", provincia: "PT", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06057", comune: "Monte Castello di Vibio", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "61010", comune: "Monte Cerignone", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "47854", comune: "Monte Colombo", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "61010", comune: "Monte Grimano Terme", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "61040", comune: "Monte Porzio", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "60030", comune: "Monte Roberto", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "40050", comune: "Monte San Pietro", provincia: "BO", giorni: ["MAR","GIO","VEN"] },
  { cap: "52048", comune: "Monte San Savino", provincia: "AR", giorni: ["MER","VEN"] },
  { cap: "60037", comune: "Monte San Vito", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06010", comune: "Monte Santa Maria Tiberina", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61020", comune: "Montecalvo in Foglia", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "60036", comune: "Montecarotto", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "51016", comune: "Montecatini-Terme", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "61024", comune: "Monteciccardo", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "61014", comune: "Montecopiolo", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "41025", comune: "Montecreto", provincia: "MO", giorni: ["MAR","VEN"] },
  { cap: "06036", comune: "Montefalco", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61030", comune: "Montefelcino", provincia: "PU", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "47834", comune: "Montefiore Conca", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "41045", comune: "Montefiorino", provincia: "MO", giorni: ["VEN"] },
  { cap: "47898", comune: "Montegiardino", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "47837", comune: "Montegridolfo", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "61025", comune: "Montelabbate", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "06045", comune: "Monteleone di Spoleto", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "50056", comune: "Montelupo Fiorentino", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "61030", comune: "Montemaggiore al Metauro", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "60018", comune: "Montemarciano", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "52010", comune: "Montemignaio", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "59013", comune: "Montemurlo", provincia: "PO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "53045", comune: "Montepulciano", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "60010", comune: "Monterado", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "52035", comune: "Monterchi", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "40050", comune: "Monterenzio", provincia: "BO", giorni: ["MAR","MER","VEN"] },
  { cap: "53035", comune: "Monteriggioni", provincia: "SI", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "53014", comune: "Monteroni d'Arbia", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "47854", comune: "Montescudo", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "41055", comune: "Montese", provincia: "MO", giorni: ["MER","VEN"] },
  { cap: "50025", comune: "Montespertoli", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "52025", comune: "Montevarchi", provincia: "AR", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40050", comune: "Monteveglio", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "47020", comune: "Montiano", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "53015", comune: "Monticiano", provincia: "SI", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06014", comune: "Montone", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40036", comune: "Monzuno", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "47833", comune: "Morciano di Romagna", provincia: "RN", giorni: ["MAR","GIO","VEN"] },
  { cap: "40027", comune: "Mordano", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "60030", comune: "Morro d'Alba", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "47890", comune: "Murata", provincia: "RSM", giorni: ["MAR","GIO","VEN"] },
  { cap: "53016", comune: "Murlo", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "06025", comune: "Nocera Umbra", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "41015", comune: "Nonantola", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06046", comune: "Norcia", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "47863", comune: "Novafeltria", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "41016", comune: "Novi di Modena", provincia: "MO", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "60026", comune: "Numana", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "45030", comune: "Occhiobello", provincia: "RO", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "60020", comune: "Offagna", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "61038", comune: "Orciano di Pesaro", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "52010", comune: "Ortignano Raggiolo", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "60027", comune: "Osimo", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44020", comune: "Ostellato", provincia: "FE", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "60010", comune: "Ostra", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "60010", comune: "Ostra Vetere", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40064", comune: "Ozzano dell'Emilia", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06060", comune: "Paciano", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "41046", comune: "Palagano", provincia: "MO", giorni: ["VEN"] },
  { cap: "50035", comune: "Palazzuolo sul Senio", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "06064", comune: "Panicale", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "06065", comune: "Passignano sul Trasimeno", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "41026", comune: "Pavullo nel Frignano", provincia: "MO", giorni: ["MAR","VEN"] },
  { cap: "61049", comune: "Peglio", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "50060", comune: "Pelago", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "47864", comune: "Pennabilli", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "52020", comune: "Pergine Valdarno", provincia: "AR", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61045", comune: "Pergola", provincia: "PU", giorni: ["MAR","GIO","SAB"] },
  { cap: "06121", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06122", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06123", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06124", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06125", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06126", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06127", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06128", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06129", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06130", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06131", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06132", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06133", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06134", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06135", comune: "Perugia", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "61121", comune: "Pesaro", provincia: "PU", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "61122", comune: "Pesaro", provincia: "PU", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "51017", comune: "Pescia", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "61020", comune: "Petriano", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "61030", comune: "Piagge", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "52026", comune: "Pian di Sco", provincia: "AR", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "53025", comune: "Piancastagnaio", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "61026", comune: "Piandimeleto", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "40065", comune: "Pianoro", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06066", comune: "Piegaro", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "53026", comune: "Pienza", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "06026", comune: "Pietralunga", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "61023", comune: "Pietrarubbia", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "51018", comune: "Pieve a Nievole", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "40066", comune: "Pieve di Cento", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "52036", comune: "Pieve Santo Stefano", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "41027", comune: "Pievepelago", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "61046", comune: "Piobbico", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "51100", comune: "Pistoia", provincia: "PT", giorni: ["MER","GIO"] },
  { cap: "51020", comune: "Piteglio", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "53036", comune: "Poggibonsi", provincia: "SI", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "59016", comune: "Poggio a Caiano", provincia: "PO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47824", comune: "Poggio Berni", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "44028", comune: "Poggio Renatico", provincia: "FE", giorni: ["MAR","GIO"] },
  { cap: "60030", comune: "Poggio San Marcello", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06040", comune: "Poggiodomo", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "45038", comune: "Polesella", provincia: "RO", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "41040", comune: "Polinago", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "60020", comune: "Polverigi", provincia: "AN", giorni: ["LUN","MER","VEN"] },
  { cap: "50065", comune: "Pontassieve", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "51019", comune: "Ponte Buggianese", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "52014", comune: "Poppi", provincia: "AR", giorni: ["MER","SAB"] },
  { cap: "40046", comune: "Porretta Terme", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "47010", comune: "Portico e San Benedetto", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "44015", comune: "Portomaggiore", provincia: "FE", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "59100", comune: "Prato", provincia: "PO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "52015", comune: "Pratovecchio", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "06047", comune: "Preci", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "47016", comune: "Predappio", provincia: "FC", giorni: ["LUN","MER","VEN"] },
  { cap: "47010", comune: "Premilcuore", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "41048", comune: "Prignano sulla Secchia", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "51039", comune: "Quarrata", provincia: "PT", giorni: ["LUN","MER","GIO","VEN","SAB"] },
  { cap: "53017", comune: "Radda in Chianti", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "53040", comune: "Radicofani", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "53030", comune: "Radicondoli", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "53040", comune: "Rapolano Terme", provincia: "SI", giorni: ["MER","VEN"] },
  { cap: "41017", comune: "Ravarino", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "48121", comune: "Ravenna", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "48122", comune: "Ravenna", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "48123", comune: "Ravenna", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "48124", comune: "Ravenna", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "48125", comune: "Ravenna", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50066", comune: "Reggello", provincia: "FI", giorni: ["MAR","GIO","SAB"] },
  { cap: "47838", comune: "Riccione", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "50067", comune: "Rignano sull'Arno", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "47921", comune: "Rimini", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47922", comune: "Rimini", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47923", comune: "Rimini", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47924", comune: "Rimini", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "48025", comune: "Riolo Terme", provincia: "RA", giorni: ["MAR","GIO"] },
  { cap: "41020", comune: "Riolunato", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "60010", comune: "Ripe", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "44030", comune: "Ro", provincia: "FE", giorni: ["MAR","GIO"] },
  { cap: "47017", comune: "Rocca San Casciano", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "47020", comune: "Roncofreddo", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "60030", comune: "Rosora", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "47891", comune: "Rovereta", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "50068", comune: "Rufina", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "48026", comune: "Russi", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40010", comune: "Sala Bolognese", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "61030", comune: "Saltara", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47835", comune: "Saludecio", provincia: "RN", giorni: ["MAR","GIO"] },
  { cap: "51020", comune: "Sambuca Pistoiese", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "40048", comune: "San Benedetto Val di Sambro", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "53040", comune: "San Casciano dei Bagni", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "50026", comune: "San Casciano in Val di Pesa", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "41018", comune: "San Cesario sul Panaro", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "47832", comune: "San Clemente", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "61039", comune: "San Costanzo", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "41038", comune: "San Felice sul Panaro", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "53037", comune: "San Gimignano", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "61030", comune: "San Giorgio di Pesaro", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "40016", comune: "San Giorgio di Piano", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "47893", comune: "San Giovanni", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "53020", comune: "San Giovanni d'Asso", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "47842", comune: "San Giovanni in Marignano", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "40017", comune: "San Giovanni in Persiceto", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "52027", comune: "San Giovanni Valdarno", provincia: "AR", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "06016", comune: "San Giustino", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "50060", comune: "San Godenzo", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "40068", comune: "San Lazzaro di Savena", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "47865", comune: "San Leo", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "61047", comune: "San Lorenzo in Campo", provincia: "PU", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "60030", comune: "San Marcello", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "51028", comune: "San Marcello Pistoiese", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "47890", comune: "San Marino", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "47030", comune: "San Mauro Pascoli", provincia: "FC", giorni: ["MAR","MER","VEN"] },
  { cap: "60038", comune: "San Paolo di Jesi", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "50037", comune: "San Piero a Sieve", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "40018", comune: "San Pietro in Casale", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "41039", comune: "San Possidonio", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "41030", comune: "San Prospero", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "53027", comune: "San Quirico d'Orcia", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "52037", comune: "Sansepolcro", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "60030", comune: "Santa Maria Nuova", provincia: "AN", giorni: ["MER","GIO","VEN"] },
  { cap: "47890", comune: "Santa Mustiola", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "47018", comune: "Santa Sofia", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "40019", comune: "Sant'Agata Bolognese", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "47866", comune: "Sant'Agata Feltria", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "48020", comune: "Sant'Agata sul Santerno", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "44047", comune: "Sant'Agostino", provincia: "FE", giorni: ["MAR","GIO"] },
  { cap: "06040", comune: "Sant'Anatolia di Narco", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "61020", comune: "Sant'Angelo in Lizzola", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "61048", comune: "Sant'Angelo in Vado", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "47822", comune: "Santarcangelo di Romagna", provincia: "RN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "61040", comune: "Sant'Ippolito", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47027", comune: "Sarsina", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "53047", comune: "Sarteano", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "40037", comune: "Sasso Marconi", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "61028", comune: "Sassocorvaro", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "61013", comune: "Sassofeltrio", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "60041", comune: "Sassoferrato", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "41049", comune: "Sassuolo", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41056", comune: "Savignano sul Panaro", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "47039", comune: "Savignano sul Rubicone", provincia: "FC", giorni: ["MAR","MER","VEN"] },
  { cap: "40060", comune: "Savigno", provincia: "BO", giorni: ["MAR","GIO"] },
  { cap: "50018", comune: "Scandicci", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "50038", comune: "Scarperia", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "06027", comune: "Scheggia e Pascelupo", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06040", comune: "Scheggino", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "06030", comune: "Sellano", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "60019", comune: "Senigallia", provincia: "AN", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "60030", comune: "Serra de' Conti", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "60048", comune: "Serra San Quirico", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "61040", comune: "Serra Sant'Abbondio", provincia: "PU", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "41028", comune: "Serramazzoni", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "47899", comune: "Serravalle", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "51030", comune: "Serravalle Pistoiese", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "61030", comune: "Serrungarina", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "52038", comune: "Sestino", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "50019", comune: "Sesto Fiorentino", provincia: "FI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41029", comune: "Sestola", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "53100", comune: "Siena", provincia: "SI", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06028", comune: "Sigillo", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "50058", comune: "Signa", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "53048", comune: "Sinalunga", provincia: "SI", giorni: ["MER","VEN"] },
  { cap: "60020", comune: "Sirolo", provincia: "AN", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47030", comune: "Sogliano al Rubicone", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "48027", comune: "Solarolo", provincia: "RA", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41019", comune: "Soliera", provincia: "MO", giorni: ["MAR","GIO"] },
  { cap: "53018", comune: "Sovicille", provincia: "SI", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06038", comune: "Spello", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "41057", comune: "Spilamberto", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "06049", comune: "Spoleto", provincia: "PG", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "60039", comune: "Staffolo", provincia: "AN", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "52017", comune: "Stia", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "52010", comune: "Subbiano", provincia: "AR", giorni: ["MAR","GIO","SAB"] },
  { cap: "47867", comune: "Talamello", provincia: "RN", giorni: ["MAR","VEN"] },
  { cap: "52010", comune: "Talla", provincia: "AR", giorni: ["GIO","SAB"] },
  { cap: "50028", comune: "Tavarnelle Val di Pesa", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "61020", comune: "Tavoleto", provincia: "PU", giorni: ["MER","VEN"] },
  { cap: "61010", comune: "Tavullia", provincia: "PU", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "47894", comune: "Teglio", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "52028", comune: "Terranuova Bracciolini", provincia: "AR", giorni: ["MAR","MER","GIO","VEN","SAB"] },
  { cap: "06059", comune: "Todi", provincia: "PG", giorni: ["MAR","GIO"] },
  { cap: "06089", comune: "Torgiano", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "47895", comune: "Torraccia", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "47825", comune: "Torriana", provincia: "RN", giorni: ["MAR","GIO"] },
  { cap: "53049", comune: "Torrita di Siena", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "47019", comune: "Tredozio", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "53020", comune: "Trequanda", provincia: "SI", giorni: ["MAR","GIO","SAB"] },
  { cap: "44039", comune: "Tresigallo", provincia: "FE", giorni: ["MAR","GIO"] },
  { cap: "06039", comune: "Trevi", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "06069", comune: "Tuoro sul Trasimeno", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "06019", comune: "Umbertide", provincia: "PG", giorni: ["LUN","MAR","MER","GIO","VEN","SAB"] },
  { cap: "61049", comune: "Urbania", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "61029", comune: "Urbino", provincia: "PU", giorni: ["MAR","MER","VEN"] },
  { cap: "51010", comune: "Uzzano", provincia: "PT", giorni: ["LUN","MER","VEN"] },
  { cap: "50036", comune: "Vaglia", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "59021", comune: "Vaiano", provincia: "PO", giorni: ["MER","VEN"] },
  { cap: "47893", comune: "Valdragone", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "06029", comune: "Valfabbrica", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "06040", comune: "Vallo di Nera", provincia: "PG", giorni: ["MAR","GIO","VEN"] },
  { cap: "06030", comune: "Valtopina", provincia: "PG", giorni: ["MAR","MER","GIO","VEN"] },
  { cap: "47893", comune: "Ventoso", provincia: "RSM", giorni: ["MAR","GIO"] },
  { cap: "40038", comune: "Vergato", provincia: "BO", giorni: ["LUN","MER","VEN"] },
  { cap: "47028", comune: "Verghereto", provincia: "FC", giorni: ["MAR","VEN"] },
  { cap: "59024", comune: "Vernio", provincia: "PO", giorni: ["GIO"] },
  { cap: "47826", comune: "Verucchio", provincia: "RN", giorni: ["MAR","MER","VEN"] },
  { cap: "50039", comune: "Vicchio", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "44049", comune: "Vigarano Mainarda", provincia: "FE", giorni: ["MAR","GIO"] },
  { cap: "41058", comune: "Vignola", provincia: "MO", giorni: ["LUN","MAR","MER","GIO","VEN"] },
  { cap: "50059", comune: "Vinci", provincia: "FI", giorni: ["MER","VEN"] },
  { cap: "44019", comune: "Voghiera", provincia: "FE", giorni: ["MAR","VEN"] },
  { cap: "41059", comune: "Zocca", provincia: "MO", giorni: ["MER","VEN"] },
  { cap: "40069", comune: "Zola Predosa", provincia: "BO", giorni: ["LUN","MAR","MER","GIO","VEN"] }
]; 

